### PR TITLE
Update the README with examples and explanations

### PR DESCRIPTION
**Pull request by dmulder**

### CODE REVIEW

**Comment by noelpower** [comment]
Should we add some info on localisation ? I can't recall myself what we discovered was necessary about this

**Comment by dmulder** [comment]
@noelpower I remember we have to `from yast import textdomain, _`, set the project name with `textdomain('proj_name')`, then wrap all text using _() function. But also some yast internationalization package has to contain the actual translations.

**Comment by noelpower** [comment]
could you add an example of this in the README, this is definitely something people are going to encounter and want to know how to deal with

**Comment by dmulder** [comment]
@noelpower I've added a description for using gettext.

**Pull request merged**
